---
- include:              '../tasks/install_packages.yml'
- include:              '../tasks/install_files.yml'
- include:              '../tasks/user_groups.yml'
  vars:
    user_groups:        "{{ usergroup_all }}"
- include:              '../tasks/users.yml'
  vars:
    users:              "{{ usergroup_all }}"
- include:              '../tasks/add_users_to_groups.yml'
  vars:
    add_users_to_groups:
      - user:           "{{ user }}"
        groups:
          - 'games'
  with_items:           "{{ usergroup_games }}"
  loop_control:
    loop_var:           'user'
- include:              'homedir.yml'
  vars:
    homedir_user:       "{{ item }}"
  with_items:           "{{ usergroup_all }}"
- include:              '../tasks/allow_users.yml'
  vars:
    allow_users:        "{{ usergroup_all }}"
