---
- include:              '../tasks/install_packages.yml'
- include:              '../tasks/install_files.yml'
- include:              '../tasks/user_groups.yml'
  vars:
    user_groups:        "{{ usergroup_all }}"
- include:              '../tasks/users.yml'
  vars:
    users:              "{{ usergroup_all }}"
- include:              '../tasks/add_users_to_groups.yml'
  vars:
    add_users_to_groups:
      - user:           "{{ item }}"
        groups:
          - 'games'
  with_items:           "{{ usergroup_games }}"
  when:                 usergroup_games is defined
- include:              '../tasks/homedirs.yml'
  vars:
    homedirs:           "{{ usergroup_all }}"
