---
- include_tasks:        'tasks/common/install_packages.yml'
- include_tasks:        'tasks/common/install_files.yml'
- include_tasks:        'tasks/common/user_groups.yml'
  vars:
    user_groups:        "{{ usergroup_all }}"
- include_tasks:        'tasks/common/users.yml'
  vars:
    users:              "{{ usergroup_all }}"
- include_tasks:        'tasks/common/add_users_to_groups.yml'
  vars:
    add_users_to_groups:
      - user:           "{{ user }}"
        groups:
          - 'games'
  with_items:           "{{ usergroup_games }}"
  loop_control:
    loop_var:           'user'
- include_tasks:        'tasks/common/allow_users.yml'
  vars:
    allow_users:        "{{ usergroup_all }}"
